status = ["ci/circleci: build_test_publish", "ci/circleci: docs"]
cut_body_after = "<details>" # Avoid including verbose details from PyUp in commit messages
block_labels = ["bors-dont-merge"]
# At the moment, this project is a single-developer project.
# Increase this to 1 when the project has more developers.
required_approvals = 0
delete_merged_branches = true
