status = ["ci/circleci"]
cut_body_after = "<details>" # Avoid including verbose details from PyUp in commit messages
block_labels = ["bors-dont-merge"]
required_approvals = 1
delete_merged_branches = true