version: "3"

services:
  db:
    image: postgres:9.6@sha256:b0082a6a11b3f35e1ad403d2a70f8492e669c7fddd529af0d1d77cfb974e2c1f
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
  elasticsearch:
    # Intent to always match
    # https://github.com/mozilla-services/cloudops-infra/blob/buildhub2/projects/buildhub2/k8s/charts/elasticsearch/values.yaml
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONTEND_SENTRY_PUBLIC_DSN
        - CI
    image: buildhub2
    depends_on:
      - db
      - elasticsearch
    environment:
      # This tells run.sh to wait for databases to be fully up.
      - DEVELOPMENT=1
      - DJANGO_CONFIGURATION=Test
      - DATABASE_URL=postgresql://postgres@db/postgres
      - DJANGO_ES_URLS=http://elasticsearch:9200
    command: test

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    command: build

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    command: build
