version: '3'

services:
  db:
    image: postgres:9.6@sha256:5beac0fe8a25cf68bb420c21fd8b213e346b9f8eaf3c7ff07bde1daa75289445
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONTEND_SENTRY_PUBLIC_DSN
        - CI
    image: buildhub2
    depends_on:
      - db
      - elasticsearch
    environment:
      - DEVELOPMENT=1
      - DJANGO_CONFIGURATION=Test
      - DATABASE_URL=postgresql://postgres@db/postgres
      - DJANGO_ES_URLS=http://elasticsearch:9200
    command: test

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    command: build

