# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#

version: 2
jobs:
  build_test_publish:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/buildhub2
    steps:
      - run:
          name: Install essential packages
          command: |
            apt-get update && apt-get install -y ca-certificates curl git openssh-client

      - checkout

      - run:
          name: Install Docker client
          command: |
            set -x
            # Latest 200 OK version as of June 2018
            # https://circleci.com/docs/2.0/building-docker-images/#docker-version
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker:
          version: 17.09.0-ce

      - run:
          name: Create version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build
          command: |
            docker-compose -f docker-compose.ci.yml build

      - run:
          name: Run web tests
          command: |
            docker-compose -f docker-compose.ci.yml run test

      - run:
          name: Lint check Python code
          command: |
            docker-compose -f docker-compose.ci.yml run test lintcheck

      - run:
          name: Run ui build
          command: |
            docker-compose -f docker-compose.ci.yml run ui

      - store_artifacts:
          path: ui/build

      - run:
          name: Push to Dockerhub
          command: |
            # set DOCKER_DEPLOY=true in Circle UI to push to Dockerhub
            DOCKER_DEPLOY="${DOCKER_DEPLOY:-false}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./bin/deploy-dockerhub.sh latest
            fi
            if [ -n "${CIRCLE_TAG}" ]; then
              ./bin/deploy-dockerhub.sh "$CIRCLE_TAG"
            fi

  docs:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/buildhub2

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "docs/requirements.txt" }}

      - run:
          name: Create virtualenv
          command: |
            python3 -m venv ~/venv
            echo "source ~/venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install requirements
          command: pip install -r docs/requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "docs/requirements.txt" }}
          paths:
            - "~/venv"

      - run:
          name: Build docs
          command: |
            cd docs
            make html

workflows:
  version: 2
  main:
    jobs:
      - build_test_publish:
          filters:
            tags:
              only: /.*/
      - docs
